### ISSUE TITLE
Cubari: generic JSON proxy

### ISSUE THREAD

**Issue by ObserverOfTime** [appu1232/cubarimoe#6]
The current gist proxy is limited to GitHub users. It would be desirable to create a generic proxy—much like the FoolSlide one—that accepts arbitrary JSON URLs (which adhere to the schema) in order to proxy any anonymous paste service. If you're OK with this idea, I can work on a PR.

**Comment by funkyhippo** [comment]
> Can't say for sure. I'm busy surviving now, optimistic estimate would be a month, I think? If that's too long of a wait for what you're trying to do, @funkyhippo could weigh in if it's possible to query JSONs through a CORS proxy and/or add another whitelisted service if needed. What do you plan to use to host the JSONs?

It's certainly possible, but, in addition to what you already pointed out, arbitrary URLs will result in some pretty long Cubari URLs since we're using the path to pass that metadata around. The foolslide proxy was very much a proof-of-concept that I wouldn't want to carry over to the rewrite since it's a pretty huge security vector; going forward, an allowlist would definitely be necessary for something like that.

> I think the general idea is to allow for the creation of (or modification of an existing) self-hosted scanlation CMS that would host the images and information, but would proxy to cubari’s superior reader for actual reading using auto-generated json.
> 
> Allowing cubari to read any properly formatted json file supplied to it (especially if you allow api-style urls and not just straight .json files) would allow such a cms to exist without messing around with the GitHub api.

For the time-being, it's entirely possible to write a shim to just mirror your CMS to GitHub. It's not ideal with a fully-featured CMS since you'll have multiple sources of truth, but it should be mostly transparent to the people who actually interact with the CMS.

For instance, I have a GH workflow that just parses the OPM Google Drive to build the gist every 15 minutes. The maintainer of the Drive doesn't need to worry about updating the gist manually, and there's zero cost to either of us since there's no paid infrastructure involved.

Interacting with the GitHub API should be trivial if you're considering modifying or writing a CMS that also dumps a JSON with the Cubari schema.

**Comment by ObserverOfTime** [comment]
I already have an API endpoint that dumps the Cubari schema but handling the GitHub part of things is *not* something I want to do (for various reasons), hence this issue.

**Comment by funkyhippo** [comment]
> I already have an API endpoint that dumps the Cubari schema but handling the GitHub part of things is _not_ something I want to do (for various reasons), hence this issue.

Fair. For curiosity's sake, do you mind sharing what those reasons are?

**Comment by ObserverOfTime** [comment]
I already mentioned one of the reasons: it's limited to GitHub users.
Other than that, the implementation is not straight-forward.

For example, how should I handle the GitHub token?
Should I add it to the group table so that every group can have its own?
Should I create a new table to bind the token with a user ID, restricted to staff members?
Should I store it in the configuration so that only the admin and whoever they share it with can use it?
Should I not store it anywhere and instead have the user supply it as a field or param with every request?

OK, say I've handled the token, where do I upload the JSON?
"To a gist" may seem like the obvious answer but…one gist per series?
Maybe a single gist with multiple files? Would a repo be better for that?
Either way, what about the name? Do I store it, and how? What should it even be?
I can use the series slug but what if it's taken? I would need to let the user change it…

After all this—and more—brainstorming, I simply decided not to bother.

**Comment by funkyhippo** [comment]
At the risk of sounding dismissive (especially since I haven't thought too much about the problem space), I do think you're overthinking it.

> I already mentioned one of the reasons: it's limited to GitHub users. Other than that, the implementation is not straight-forward.

This is true, but it's no different from depending on an external service for any part of your application. For example, you'll need an AWS account and the appropriate credentials if you're hosting your database on DynamoDB. Since it sounds like you're using Cubari as the series and reader interface, it seems appropriate to require some external credential.

> For example, how should I handle the GitHub token?

You can store it as a secret embedded in your application, like a database credential.

> Should I add it to the group table so that every group can have its own? Should I create a new table to bind the token with a user ID, restricted to staff members? Should I store it in the configuration so that only the admin and whoever they share it with can use it? Should I not store it anywhere and instead have the user supply it as a field or param with every request?

None of these should be problems you'll have to deal with since the token should interact at a lower level of the stack. You can substitute "database token" for all of these questions and it suddenly wouldn't make sense.

> OK, say I've handled the token, where do I upload the JSON? "To a gist" may seem like the obvious answer but…one gist per series? Maybe a single gist with multiple files? Would a repo be better for that? Either way, what about the name? Do I store it, and how? What should it even be?

You can store it in a repo. Despite the proxy's name, you're not limited to just gists since you can point to any resource hosted on GitHub (though this one is definitely a fault of the proxy since the naming doesn't easily convey this).

The name of the file doesn't matter since you're creating a pointer to it with git.io -- you can use the randomly generated string or pass your own for this.

> I can use the series slug but what if it's taken? I would need to let the user change it…

This is a valid problem; the shortcodes and custom names with git.io are immutable, so if you're issued a takedown, those links suddenly stop working.
